name: Greetings

on: [pull_request_target]

jobs:
    greeting:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        if: ${{ github.actor != 'dependabot[bot]' }}
        steps:
            - uses: actions/first-interaction@v2
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pr-message: 'Congrats on your first PR 😎!'
