name: Create release in GitHub
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
    publish_gh_release:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - run: |
                  echo "Tag version: ${{github.ref_name}}"
                  gh release create ${{github.ref_name}} --generate-notes --verify-tag
                  echo "Release ${{github.ref_name}} created"
